// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'app_page.dart' as a3;
import 'guarded/guarded_page.dart' as a0;
import 'users/[id]_page.dart' as a1;
import 'users/users_page.dart' as a2;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a0.GuardedPage(),
    );
Route b1Builder(BuildContext context, RouteSettings settings) =>
    a1.routeBuilder(context, settings);
Route b2Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a2.UsersPage(),
    );
Route b3Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a3.AppPage(),
    );
