// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: 'guarded',
        uri: Uri.parse('guarded'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: 'users/[id]',
        uri: Uri.parse('users/[id]'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: 'users',
        uri: Uri.parse('users'),
        routeBuilder: b2Builder,
      ),
      RouteEntity(
        key: 'lib/app',
        uri: Uri.parse('lib/app'),
        routeBuilder: b3Builder,
      ),
    ];

const routePaths = (
  path: '/',
  guarded: '/guarded',
  users: (
    path: '/users',
    $id: '/users/[id]',
  ),
  lib: (
    path: '/lib',
    app: '/lib/app',
  ),
);
