// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'app_page.dart' as a4;
import 'dashboard/dashboard_layout.dart' as a1;
import 'dashboard/option1_page.dart' as a0;
import 'dashboard/option2_page.dart' as a2;
import 'dashboard/option3_page.dart' as a3;

Route b0Builder(BuildContext context, RouteSettings settings) =>
    a0.routeBuilder(context, settings);
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a1.DashboardLayout(),
    );
Route b2Builder(BuildContext context, RouteSettings settings) =>
    a2.routeBuilder(context, settings);
Route b3Builder(BuildContext context, RouteSettings settings) =>
    a3.routeBuilder(context, settings);
Route b4Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a4.AppPage(),
    );
