// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: 'dashboard/option1',
        parent: 'dashboard',
        uri: Uri.parse('dashboard/option1'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: 'dashboard',
        uri: Uri.parse('dashboard'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: 'dashboard/option2',
        parent: 'dashboard',
        uri: Uri.parse('dashboard/option2'),
        routeBuilder: b2Builder,
      ),
      RouteEntity(
        key: 'dashboard/option3',
        parent: 'dashboard',
        uri: Uri.parse('dashboard/option3'),
        routeBuilder: b3Builder,
      ),
      RouteEntity(
        key: 'lib/app',
        uri: Uri.parse('lib/app'),
        routeBuilder: b4Builder,
      ),
    ];

const routePaths = (
  path: '/',
  dashboard: (
    path: '/dashboard',
    option1: '/dashboard/option1',
    option2: '/dashboard/option2',
    option3: '/dashboard/option3',
  ),
  lib: (
    path: '/lib',
    app: '/lib/app',
  ),
);
